[data]
source = "MSSCS_experiments"
path = "21-01-26_SCBA_SCS1_detail65K"

[plot]
show_cfg = false
# ignore_shims = ['L1', 'L2', 'R2', 'R3']

[scb_analysis]
# filter_threshold_mV = 5.0
# analyse_SCBAs = false
ignore_before_t0 = true
# index_range_to_analyse = [0,2]
[scb_analysis.all_pulse_analysis_plot]
vpp_range = [3, 5]

