[[mounts]]
source_name = "MSSCS_experiments"
remote_path = "21-02-26_SCBA_SCS4_evenmoredetail72.5K"
mount_path = ''

[plot]
show_cfg = false
# ignore_shims = ['L1', 'L2', 'R2', 'R3']
[scb_analysis]
# analyse_SCBAs = false
