[data]
source = "MSSCS_experiments"
path = "21-01-26_SCBA_SCS1_detail65K"

[plot]
show_cfg = false
# ignore_shims = ['L1', 'L2', 'R2', 'R3']

[scb_analysis]
# filter_threshold_mV = 5.0
analyse_SCBAs = false
all_pulse_analysis_vpp_range = [3, 5]