[[mounts]]
source_name = "MSSCS_experiments"
remote_path = "11-05-26_SCS_breaking_pulse_length_scanning"
mount_path = '11-05-26_SCS_breaking_pulse_length_scanning'

[[mounts]]
source_name = "MSSCS_experiments"
remote_path = "12-05-26_SCS2_pedestal_scanning"
mount_path = '12-05-26_SCS2_pedestal_scanning'

[[mounts]]
source_name = "MSSCS_experiments"
remote_path = "14-05-26_repetition_study"
mount_path = '14-05-26_repetition_study'


[plot]
show_cfg = false
# ignore_shims = ['L1', 'L2', 'R2', 'R3']

[scb_analysis]
# filter_threshold_mV = 5.0
# analyse_SCBAs = false
ignore_before_t0 = false
# pulse_crop_margin_frac = {idle: 0.05, pulse: 0.05}
# plot_pulses = true
# index_range_to_analyse = [20, 65]


[scb_analysis.all_pulse_analysis_plot]
# vpp_range = [3, 4]
# show_error_bars = false
