[[mounts]]
source_name = "MSSCS_experiments"
remote_path = "25-03-26_SCS1_at_70K"
mount_path = ''

[plot]
show_cfg = false
# ignore_shims = ['L1', 'L2', 'R2', 'R3']

[scb_analysis]
# filter_threshold_mV = 5.0
# analyse_SCBAs = false
ignore_before_t0 = false
# pulse_crop_margin_frac = {idle: 0.05, pulse: 0.05}
plot_pulses = true
# index_range_to_analyse = [20, 65]


[scb_analysis.all_pulse_analysis_plot]
# vpp_range = [3, 5]
# show_error_bars = false
